# # .devcontainer/Dockerfile
# FROM node:23.11.0-bullseye-slim

# # # Install git
# # RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# # # Set working directory
# # WORKDIR /workspace

# # # figma-developer-mcp のインストール
# # RUN npm install -g figma-developer-mcp

# # # MCP サーバーの起動コマンド
# # CMD ["figma-developer-mcp", "--figma-api-key", "YOUR_FIGMA_API_KEY", "--port", "3333"]

# WORKDIR /app

# RUN npm install -g figma-developer-mcp

# CMD ["figma-developer-mcp", "--port", "3001"]